### PR TITLE
Dependencies to include Python 3.10.* and 3.11.*

### PR DESCRIPTION
**Pull request by mikulas-mrva**
Updating dependencies to include all minor and patch versions of Python 3.10 and 3.11 (released a few days ago).

### CODE REVIEW

**Comment by hisdream86** [comment]
Thanks for your job. However, this change has been applied at #5.

So I'd like to close this PR.

**Comment by mikulas-mrva** [comment]
@hisdream86 my branch also added support of python 3.11 that was released recently and should be fairly backwards-compatible, do you have a specific reason to restrict it?

**Comment by hisdream86** [comment]
@mikulas-mrva 

Sorry for the late reply 🙇‍♂️ 

I referred to the [DRF requirements](https://www.django-rest-framework.org/#requirements) to check the supported python version of the DRF and found the latest version of python is 3.10

image

After your comment, I tried to check more detail and found no upper bound after [DRF 3.13](https://www.django-rest-framework.org/community/3.13-announcement/). Moreover, I checked it is working well over python 3.11.

For this reason, I will remove the upper bound for this package as well.

**Comment by hisdream86** [comment]
It is possible to use python 3.11 from the [v0.2.3](https://pypi.org/project/drfasyncview/0.2.3/).

**Pull request closed without merging**
